### ISSUE TITLE
FileProvider Security Issues

### ISSUE THREAD

**Issue by c2digital** [janishar/ParaCamera#10]
API 16

App crashes due to File Provider security issue:-

```
02-25 16:49:46.281 1371-1371/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 java.lang.IllegalStateException: Could not execute method of the activity
                                                     at android.view.View$1.onClick(View.java:3591)
                                                     at android.view.View.performClick(View.java:4084)
                                                     at android.view.View$PerformClick.run(View.java:16966)
                                                     at android.os.Handler.handleCallback(Handler.java:615)
                                                     at android.os.Handler.dispatchMessage(Handler.java:92)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at android.view.View$1.onClick(View.java:3586)
                                                     at android.view.View.performClick(View.java:4084) 
                                                     at android.view.View$PerformClick.run(View.java:16966) 
                                                     at android.os.Handler.handleCallback(Handler.java:615) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{537e1d30 1371:com.android.camera/u0a22} (pid=1371, uid=10022) that is not exported from uid 10048
                                                     at android.os.Parcel.readException(Parcel.java:1425)
                                                     at android.os.Parcel.readException(Parcel.java:1379)
                                                     at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:2354)
                                                     at android.app.ActivityThread.acquireProvider(ActivityThread.java:4219)
                                                     at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:1711)
                                                     at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1099)
                                                     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:614)
                                                     at android.content.ContentResolver.openOutputStream(ContentResolver.java:487)
                                                     at android.content.ContentResolver.openOutputStream(ContentResolver.java:463)
                                                     at com.android.camera.Camera.doAttach(Camera.java:1385)
                                                     at com.android.camera.Camera.onReviewDoneClicked(Camera.java:1362)
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at android.view.View$1.onClick(View.java:3586) 
                                                     at android.view.View.performClick(View.java:4084) 
                                                     at android.view.View$PerformClick.run(View.java:16966) 
                                                     at android.os.Handler.handleCallback(Handler.java:615) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                     at dalvik.system.NativeStart.main(Native Method) 

```

**Comment by janishar** [comment]
@caphson 
What is the version of the library you are currently using?

**Comment by ajit-sharma** [comment]
Error : - java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider
App version 0.2.1 <compile 'com.mindorks:paracamera:0.2.1'>

1)  lava iris460 (4.4.2) Not working
2) Sony D2202 (4.4.4 API 19) Not working
3) Lenovo K50A40 (6.0 AP 23)  Working after runtime permission support..

**Comment by janishar** [comment]
This bug has been fixed. Please use version 0.2.2

See the release Note:
https://github.com/janishar/ParaCamera/releases/tag/0.2.2
